/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pvi_ap_reader_external_pdf_pdfReader */

#ifndef _Included_com_pvi_ap_reader_external_pdf_pdfReader
#define _Included_com_pvi_ap_reader_external_pdf_pdfReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pvi_ap_reader_external_pdf_pdfReader
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_pvi_ap_reader_external_pdf_pdfReader_init
  (JNIEnv *, jobject);

/*
 * Class:     com_pvi_ap_reader_external_pdf_pdfReader
 * Method:    setViewPortSize
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pvi_ap_reader_external_pdf_pdfReader_setViewPortSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_pvi_ap_reader_external_pdf_pdfReader
 * Method:    setCache
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pvi_ap_reader_external_pdf_pdfReader_setCache
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_pvi_ap_reader_external_pdf_pdfReader
 * Method:    open
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pvi_ap_reader_external_pdf_pdfReader_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_pvi_ap_reader_external_pdf_pdfReader
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_pvi_ap_reader_external_pdf_pdfReader_close
  (JNIEnv *, jobject);

/*
 * Class:     com_pvi_ap_reader_external_pdf_pdfReader
 * Method:    getBitmapStuff
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_pvi_ap_reader_external_pdf_pdfReader_getBitmapStuff
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_pvi_ap_reader_external_pdf_pdfReader
 * Method:    getCurrentPage
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_pvi_ap_reader_external_pdf_pdfReader_getCurrentPage
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_pvi_ap_reader_external_pdf_pdfReader
 * Method:    getPageCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_pvi_ap_reader_external_pdf_pdfReader_getPageCount
  (JNIEnv *, jobject);

/*
 * Class:     com_pvi_ap_reader_external_pdf_pdfReader
 * Method:    getNaturalSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_pvi_ap_reader_external_pdf_pdfReader_getNaturalSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_pvi_ap_reader_external_pdf_pdfReader
 * Method:    gotoPage
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pvi_ap_reader_external_pdf_pdfReader_gotoPage
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_pvi_ap_reader_external_pdf_pdfReader
 * Method:    gotoPrevScreenPage
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_pvi_ap_reader_external_pdf_pdfReader_gotoPrevScreenPage
  (JNIEnv *, jobject);

/*
 * Class:     com_pvi_ap_reader_external_pdf_pdfReader
 * Method:    gotoNextScreenPage
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_pvi_ap_reader_external_pdf_pdfReader_gotoNextScreenPage
  (JNIEnv *, jobject);

/*
 * Class:     com_pvi_ap_reader_external_pdf_pdfReader
 * Method:    setFontSize
 * Signature: (D)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pvi_ap_reader_external_pdf_pdfReader_setFontSize
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_pvi_ap_reader_external_pdf_pdfReader
 * Method:    getChapterList
 * Signature: (I)[Lcom/pvi/ap/reader/external/pdf/ChapterInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_com_pvi_ap_reader_external_pdf_pdfReader_getChapterList
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_pvi_ap_reader_external_pdf_pdfReader
 * Method:    getChapterListLen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_pvi_ap_reader_external_pdf_pdfReader_getChapterListLen
  (JNIEnv *, jobject);

/*
 * Class:     com_pvi_ap_reader_external_pdf_pdfReader
 * Method:    hasTableOfContent
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_pvi_ap_reader_external_pdf_pdfReader_hasTableOfContent
  (JNIEnv *, jobject);

/*
 * Class:     com_pvi_ap_reader_external_pdf_pdfReader
 * Method:    autoCutMargin
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pvi_ap_reader_external_pdf_pdfReader_autoCutMargin
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_pvi_ap_reader_external_pdf_pdfReader
 * Method:    setFitMode
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pvi_ap_reader_external_pdf_pdfReader_setFitMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_pvi_ap_reader_external_pdf_pdfReader
 * Method:    setViewPort
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pvi_ap_reader_external_pdf_pdfReader_setViewPort
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_pvi_ap_reader_external_pdf_pdfReader
 * Method:    setPagingMode
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pvi_ap_reader_external_pdf_pdfReader_setPagingMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_pvi_ap_reader_external_pdf_pdfReader
 * Method:    setScrollOffset
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pvi_ap_reader_external_pdf_pdfReader_setScrollOffset
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_pvi_ap_reader_external_pdf_pdfReader
 * Method:    search
 * Signature: (Ljava/lang/String;ZII)I
 */
JNIEXPORT jint JNICALL Java_com_pvi_ap_reader_external_pdf_pdfReader_search
  (JNIEnv *, jobject, jstring, jboolean, jint, jint);

/*
 * Class:     com_pvi_ap_reader_external_pdf_pdfReader
 * Method:    docReachHeadOrTail
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pvi_ap_reader_external_pdf_pdfReader_docReachHeadOrTail
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
